"""
Strategy Parameters - Generated from params_to_optimize.md

This file is AUTO-GENERATED by strategy_params_generator.py
DO NOT EDIT MANUALLY - Changes will be overwritten

To modify parameters:
1. Edit workspace/current/strategy/params_to_optimize.md
2. Run: python -m modules.backtest.backtrader_strategy.platform_agnostic.strategy_params_generator
3. Validate output with parameter_agent.py
"""

from typing import List, Dict, Any
import optuna
from ...core.base.parameter_architecture import (
    ComponentParameterTemplate,
    ParameterSpec,
    ParameterType,
    StrategyParameterFramework
)



class EntryParameters(ComponentParameterTemplate):
    """Parameter definitions for entry component"""

    def get_component_name(self) -> str:
        return 'entry'

    def define_parameters(self) -> List[ParameterSpec]:
        return [
        ParameterSpec(
            name="aroonosc_period",
            param_type=ParameterType.FIXED,
            default_value=16,
            description="Aroon Oscillator period for trending_up long (preserved Tier 1 calculation parameter fixed per baseline)."
        ),
        ParameterSpec(
            name="trix_period",
            param_type=ParameterType.FIXED,
            default_value=15,
            description="TRIX period for trending_up short (preserved Tier 1 calculation parameter fixed per baseline)."
        ),
        ParameterSpec(
            name="atr_14_period",
            param_type=ParameterType.INT,
            default_value=14,
            min_value=10,
            max_value=20,
            description="ATR period for trending_down long (preserved Tier 1 calculation parameter)."
        ),
        ParameterSpec(
            name="mfi_14_period",
            param_type=ParameterType.FIXED,
            default_value=14,
            description="MFI period for trending_down long (preserved Tier 1 calculation parameter fixed per baseline)."
        ),
        ParameterSpec(
            name="tema_period",
            param_type=ParameterType.FIXED,
            default_value=20,
            description="TEMA period for ranging short (preserved Tier 1 calculation parameter fixed per baseline)."
        ),
        ParameterSpec(
            name="entry_ppo_trending_down_short_threshold",
            param_type=ParameterType.FLOAT,
            default_value=0.45,
            min_value=0.3,
            max_value=0.6,
            description="[NARROWED by HYP_001] PPO threshold for trending_down short entry. Range lowered from [0.55, 0.8] to [0.3, 0.6] to increase short trade proportion from 14.8% toward >25%."
        ),
        ParameterSpec(
            name="aroonosc_long_threshold",
            param_type=ParameterType.FIXED,
            default_value=12.0,
            description="Aroon Oscillator threshold for trending_up long (preserved)."
        ),
        ParameterSpec(
            name="entry_trix_trending_up_short_threshold",
            param_type=ParameterType.FIXED,
            default_value=0.0295774542666676,
            description="TRIX threshold for trending_up short (preserved)."
        ),
        ParameterSpec(
            name="entry_atr_trending_down_long_threshold",
            param_type=ParameterType.FIXED,
            default_value=100.0,
            description="ATR threshold for trending_down long (preserved)."
        ),
        ParameterSpec(
            name="entry_mfi_trending_down_long_threshold",
            param_type=ParameterType.FIXED,
            default_value=38.0,
            description="MFI threshold for trending_down long (preserved)."
        ),
        ParameterSpec(
            name="macd_histogram_ranging_long_threshold",
            param_type=ParameterType.FIXED,
            default_value=0.1685,
            description="MACD histogram threshold for ranging long (preserved Tier 2 usage param fixed per baseline)."
        ),
        ParameterSpec(
            name="entry_tema_ranging_short_threshold",
            param_type=ParameterType.FIXED,
            default_value=19250.38045813741,
            description="TEMA threshold for ranging short (preserved)."
        ),
        ParameterSpec(
            name="entry_macd_histogram_volatile_long_threshold",
            param_type=ParameterType.FIXED,
            default_value=-0.3565222105032799,
            description="MACD histogram threshold for volatile long (preserved Tier 2 usage param fixed per baseline)."
        ),
        ParameterSpec(
            name="entry_ad_short_threshold",
            param_type=ParameterType.FIXED,
            default_value=0.0,
            description="AD threshold for volatile short only (preserved Tier 3 usage param)."
        ),
        ParameterSpec(
            name="ppo_fast_period",
            param_type=ParameterType.FIXED,
            default_value=12,
            description="Documented PPO internal default fast period for Tier 2 PPO. Not a calculation parameter because Tier 2 calculation section must remain free of PPO params."
        ),
        ParameterSpec(
            name="ppo_slow_period",
            param_type=ParameterType.FIXED,
            default_value=26,
            description="Documented PPO internal default slow period for Tier 2 PPO. Not a calculation parameter because Tier 2 calculation section must remain free of PPO params."
        )
        ]



class ExitParameters(ComponentParameterTemplate):
    """Parameter definitions for exit component"""

    def get_component_name(self) -> str:
        return 'exit'

    def define_parameters(self) -> List[ParameterSpec]:
        return [
        ParameterSpec(
            name="exit_atr_period",
            param_type=ParameterType.INT,
            default_value=17,
            min_value=10,
            max_value=30,
            description="ATR calculation period for exit distance measurement (Tier 1 ATR, owner exit)."
        ),
        ParameterSpec(
            name="exit_trending_down_long_stop_mult",
            param_type=ParameterType.FLOAT,
            default_value=1.251777572010964,
            min_value=1.0,
            max_value=2.5,
            description="Stop loss ATR multiplier for trending_down long (preserved)."
        ),
        ParameterSpec(
            name="exit_trending_down_long_target_mult",
            param_type=ParameterType.FLOAT,
            default_value=1.407768360532882,
            min_value=1.0,
            max_value=2.5,
            description="Profit target ATR multiplier for trending_down long (preserved)."
        ),
        ParameterSpec(
            name="exit_trending_down_long_max_bars",
            param_type=ParameterType.FLOAT,
            default_value=2.577295803990868,
            min_value=2.0,
            max_value=6.0,
            description="Maximum holding bars for trending_down long (preserved)."
        ),
        ParameterSpec(
            name="exit_trending_down_short_stop_mult",
            param_type=ParameterType.FLOAT,
            default_value=1.571,
            min_value=1.0,
            max_value=2.5,
            description="Stop loss ATR multiplier for trending_down short. Proposed as FLOAT by exit CASCADE, but this conflicts with baseline FIXED classification and is flagged in report."
        ),
        ParameterSpec(
            name="exit_trending_down_short_target_mult",
            param_type=ParameterType.FLOAT,
            default_value=2.5,
            min_value=1.0,
            max_value=2.5,
            description="Profit target ATR multiplier for trending_down short. Proposed as FLOAT by exit CASCADE. Default clamped from source 3.207 to max_value 2.5."
        ),
        ParameterSpec(
            name="exit_trending_up_long_stop_mult",
            param_type=ParameterType.FIXED,
            default_value=1.571,
            description="Stop loss ATR multiplier for trending_up long (preserved)."
        ),
        ParameterSpec(
            name="exit_trending_up_long_target_mult",
            param_type=ParameterType.FIXED,
            default_value=3.207,
            description="Profit target ATR multiplier for trending_up long (preserved)."
        ),
        ParameterSpec(
            name="exit_trending_up_short_stop_mult",
            param_type=ParameterType.FIXED,
            default_value=1.2,
            description="Stop loss ATR multiplier for trending_up short (preserved)."
        ),
        ParameterSpec(
            name="exit_trending_up_short_target_mult",
            param_type=ParameterType.FIXED,
            default_value=1.5,
            description="Profit target ATR multiplier for trending_up short (preserved)."
        ),
        ParameterSpec(
            name="exit_trending_up_short_max_bars",
            param_type=ParameterType.FIXED,
            default_value=3.0,
            description="Maximum holding bars for trending_up short (preserved)."
        ),
        ParameterSpec(
            name="exit_ranging_long_stop_mult",
            param_type=ParameterType.FIXED,
            default_value=0.919,
            description="Stop loss ATR multiplier for ranging long (preserved)."
        ),
        ParameterSpec(
            name="exit_ranging_long_target_mult",
            param_type=ParameterType.FIXED,
            default_value=1.098,
            description="Profit target ATR multiplier for ranging long (preserved)."
        ),
        ParameterSpec(
            name="exit_ranging_long_max_bars",
            param_type=ParameterType.FIXED,
            default_value=4.8,
            description="Maximum holding bars for ranging long (preserved)."
        ),
        ParameterSpec(
            name="exit_ranging_short_stop_mult",
            param_type=ParameterType.FIXED,
            default_value=0.9,
            description="Stop loss ATR multiplier for ranging short (preserved)."
        ),
        ParameterSpec(
            name="exit_ranging_short_target_mult",
            param_type=ParameterType.FIXED,
            default_value=1.1,
            description="Profit target ATR multiplier for ranging short (preserved)."
        ),
        ParameterSpec(
            name="exit_ranging_short_max_bars",
            param_type=ParameterType.FIXED,
            default_value=5.0,
            description="Maximum holding bars for ranging short (preserved)."
        ),
        ParameterSpec(
            name="exit_volatile_long_stop_mult",
            param_type=ParameterType.FIXED,
            default_value=2.5,
            description="Stop loss ATR multiplier for volatile long (preserved)."
        ),
        ParameterSpec(
            name="exit_volatile_long_target_mult",
            param_type=ParameterType.FIXED,
            default_value=1.8,
            description="Profit target ATR multiplier for volatile long (preserved)."
        ),
        ParameterSpec(
            name="exit_volatile_long_max_bars",
            param_type=ParameterType.FIXED,
            default_value=4.0,
            description="Maximum holding bars for volatile long (preserved)."
        ),
        ParameterSpec(
            name="exit_volatile_short_stop_mult",
            param_type=ParameterType.FIXED,
            default_value=2.948,
            description="Stop loss ATR multiplier for volatile short (preserved)."
        ),
        ParameterSpec(
            name="exit_volatile_short_target_mult",
            param_type=ParameterType.FIXED,
            default_value=1.77,
            description="Profit target ATR multiplier for volatile short (preserved)."
        ),
        ParameterSpec(
            name="exit_volatile_short_max_bars",
            param_type=ParameterType.FIXED,
            default_value=3.83,
            description="Maximum holding bars for volatile short (preserved)."
        )
        ]



class RiskParameters(ComponentParameterTemplate):
    """Parameter definitions for risk component"""

    def get_component_name(self) -> str:
        return 'risk'

    def define_parameters(self) -> List[ParameterSpec]:
        return [
        ParameterSpec(
            name="max_drawdown_pct",
            param_type=ParameterType.FIXED,
            default_value=15.0,
            description="Hard circuit breaker threshold - portfolio drawdown percentage that triggers permanent trading halt until manual restart. Kept fixed per baseline classification."
        ),
        ParameterSpec(
            name="max_concurrent_positions",
            param_type=ParameterType.FIXED,
            default_value=1,
            description="Maximum concurrent positions allowed (single-position constraint enforced via can_trade gating)."
        )
        ]



class SizerParameters(ComponentParameterTemplate):
    """Parameter definitions for sizer component"""

    def get_component_name(self) -> str:
        return 'sizer'

    def define_parameters(self) -> List[ParameterSpec]:
        return [
        ParameterSpec(
            name="exit_atr_period",
            param_type=ParameterType.INT,
            default_value=17,
            min_value=10,
            max_value=30,
            description="ATR period shared from exit for stop distance calculation; corrected to match exit owner baseline 17. [SHARED with: exit]"
        ),
        ParameterSpec(
            name="risk_per_trade_pct",
            param_type=ParameterType.FLOAT,
            default_value=2.0944950148668005,
            min_value=1.8,
            max_value=2.5,
            description="Percentage of portfolio value risked per trade (infrastructure FLOAT preserved)."
        ),
        ParameterSpec(
            name="max_position_lots",
            param_type=ParameterType.FLOAT,
            default_value=5.0,
            min_value=5.0,
            max_value=8.0,
            description="Maximum position size in lots (infrastructure FLOAT preserved)."
        ),
        ParameterSpec(
            name="marginal_rounding_threshold",
            param_type=ParameterType.FLOAT,
            default_value=0.6596058416826159,
            min_value=0.3,
            max_value=0.7,
            description="Threshold for marginal rounding rescue; required futures sizing infrastructure parameter."
        ),
        ParameterSpec(
            name="exit_trending_up_long_stop_mult",
            param_type=ParameterType.FLOAT,
            default_value=1.571,
            min_value=1.571,
            max_value=1.571,
            description="Shared stop multiplier from exit used for sizing trending_up long. [SHARED with: exit]"
        ),
        ParameterSpec(
            name="exit_trending_up_short_stop_mult",
            param_type=ParameterType.FLOAT,
            default_value=1.2,
            min_value=1.2,
            max_value=1.2,
            description="Shared stop multiplier from exit used for sizing trending_up short. [SHARED with: exit]"
        ),
        ParameterSpec(
            name="exit_trending_down_long_stop_mult",
            param_type=ParameterType.FLOAT,
            default_value=1.251777572010964,
            min_value=1.0,
            max_value=2.5,
            description="Shared stop multiplier from exit used for sizing trending_down long. [SHARED with: exit]"
        ),
        ParameterSpec(
            name="exit_trending_down_short_stop_mult",
            param_type=ParameterType.FLOAT,
            default_value=1.571,
            min_value=1.0,
            max_value=2.5,
            description="Shared stop multiplier from exit used for sizing trending_down short; note source attempted FIXED→FLOAT conversion versus baseline. [SHARED with: exit]"
        ),
        ParameterSpec(
            name="exit_ranging_long_stop_mult",
            param_type=ParameterType.FLOAT,
            default_value=0.919,
            min_value=0.919,
            max_value=0.919,
            description="Shared stop multiplier from exit used for sizing ranging long. [SHARED with: exit]"
        ),
        ParameterSpec(
            name="exit_ranging_short_stop_mult",
            param_type=ParameterType.FLOAT,
            default_value=0.9,
            min_value=0.9,
            max_value=0.9,
            description="Shared stop multiplier from exit used for sizing ranging short. [SHARED with: exit]"
        ),
        ParameterSpec(
            name="exit_volatile_long_stop_mult",
            param_type=ParameterType.FLOAT,
            default_value=2.5,
            min_value=2.5,
            max_value=2.5,
            description="Shared stop multiplier from exit used for sizing volatile long. [SHARED with: exit]"
        ),
        ParameterSpec(
            name="exit_volatile_short_stop_mult",
            param_type=ParameterType.FLOAT,
            default_value=2.948,
            min_value=2.948,
            max_value=2.948,
            description="Shared stop multiplier from exit used for sizing volatile short. [SHARED with: exit]"
        ),
        ParameterSpec(
            name="volatile_regime_size_floor",
            param_type=ParameterType.FLOAT,
            default_value=3.5,
            min_value=2.5,
            max_value=4.5,
            description="[HYP_001] Minimum position size (lots) for volatile regime trades. Addresses inverse volatility penalty that undersizes high-alpha volatile pathway (PF 14.89)."
        ),
        ParameterSpec(
            name="contract_multiplier",
            param_type=ParameterType.FIXED,
            default_value=5,
            description="SHFE Aluminum futures contract size: 5 tons per lot (structural)."
        ),
        ParameterSpec(
            name="initial_capital",
            param_type=ParameterType.FIXED,
            default_value=200000.0,
            description="Initial portfolio value in RMB (structural)."
        )
        ]



# Initialize framework and register components
framework = StrategyParameterFramework()
framework.register_component(EntryParameters())
framework.register_component(ExitParameters())
framework.register_component(RiskParameters())
framework.register_component(SizerParameters())

# Generate default parameter structure
DEFAULT_PARAMS = framework.compose_default_strategy()

# Add shared parameters: copy from owner components
DEFAULT_PARAMS['sizer_params']['exit_atr_period'] = DEFAULT_PARAMS['exit_params']['exit_atr_period']
DEFAULT_PARAMS['sizer_params']['exit_trending_up_long_stop_mult'] = DEFAULT_PARAMS['exit_params']['exit_trending_up_long_stop_mult']
DEFAULT_PARAMS['sizer_params']['exit_trending_up_short_stop_mult'] = DEFAULT_PARAMS['exit_params']['exit_trending_up_short_stop_mult']
DEFAULT_PARAMS['sizer_params']['exit_trending_down_long_stop_mult'] = DEFAULT_PARAMS['exit_params']['exit_trending_down_long_stop_mult']
DEFAULT_PARAMS['sizer_params']['exit_trending_down_short_stop_mult'] = DEFAULT_PARAMS['exit_params']['exit_trending_down_short_stop_mult']
DEFAULT_PARAMS['sizer_params']['exit_ranging_long_stop_mult'] = DEFAULT_PARAMS['exit_params']['exit_ranging_long_stop_mult']
DEFAULT_PARAMS['sizer_params']['exit_ranging_short_stop_mult'] = DEFAULT_PARAMS['exit_params']['exit_ranging_short_stop_mult']
DEFAULT_PARAMS['sizer_params']['exit_volatile_long_stop_mult'] = DEFAULT_PARAMS['exit_params']['exit_volatile_long_stop_mult']
DEFAULT_PARAMS['sizer_params']['exit_volatile_short_stop_mult'] = DEFAULT_PARAMS['exit_params']['exit_volatile_short_stop_mult']



def get_shared_params_mapping() -> Dict[str, Dict[str, Any]]:
    """
    Returns the mapping of shared parameters between components.

    This function is AUTO-GENERATED based on params_to_optimize.json ownership.
    Used by select_best_trial.py to apply optimized values from owner to shared params.

    Returns:
        Dict mapping param_name to {'owner': component_name, 'owner_param': owner_param_name, 'shared_by': [component_names]}
    """
    return {
        "exit_atr_period": {"owner": "exit", "owner_param": "exit_atr_period", "shared_by": ['sizer']},
        "exit_trending_up_long_stop_mult": {"owner": "exit", "owner_param": "exit_trending_up_long_stop_mult", "shared_by": ['sizer']},
        "exit_trending_up_short_stop_mult": {"owner": "exit", "owner_param": "exit_trending_up_short_stop_mult", "shared_by": ['sizer']},
        "exit_trending_down_long_stop_mult": {"owner": "exit", "owner_param": "exit_trending_down_long_stop_mult", "shared_by": ['sizer']},
        "exit_trending_down_short_stop_mult": {"owner": "exit", "owner_param": "exit_trending_down_short_stop_mult", "shared_by": ['sizer']},
        "exit_ranging_long_stop_mult": {"owner": "exit", "owner_param": "exit_ranging_long_stop_mult", "shared_by": ['sizer']},
        "exit_ranging_short_stop_mult": {"owner": "exit", "owner_param": "exit_ranging_short_stop_mult", "shared_by": ['sizer']},
        "exit_volatile_long_stop_mult": {"owner": "exit", "owner_param": "exit_volatile_long_stop_mult", "shared_by": ['sizer']},
        "exit_volatile_short_stop_mult": {"owner": "exit", "owner_param": "exit_volatile_short_stop_mult", "shared_by": ['sizer']},
    }


def apply_shared_params(params: Dict[str, Any]) -> Dict[str, Any]:
    """
    Apply shared parameter values from owner components to all shared components.

    This function is AUTO-GENERATED. It copies optimized parameter values from
    the owner component to all components that share that parameter.

    Handles differently-named shared parameters (e.g., exit_atr_period → sizer_atr_period).

    Args:
        params: Parameter dict with keys like 'component_paramname' (e.g., 'exit_atr_period')

    Returns:
        Updated params dict with shared params filled from owner's values
    """
    shared_mapping = get_shared_params_mapping()

    for param_name, info in shared_mapping.items():
        owner_param = info['owner_param']

        if owner_param in params:
            source_value = params[owner_param]
            params[param_name] = source_value

    return params



def optuna_search_space(trial: optuna.Trial) -> Dict[str, Any]:
    """
    Generate parameter search space for Optuna optimization.

    This function is AUTO-GENERATED with crossover constraints to prevent
    identical period values that cause zero-trade scenarios.
    """
    params = {}

    # Component parameters

    # Entry parameters
    entry_params = {}
    entry_params["aroonosc_period"] = 16
    entry_params["trix_period"] = 15
    entry_params["atr_14_period"] = trial.suggest_int("entry_atr_14_period", 10, 20)
    entry_params["mfi_14_period"] = 14
    entry_params["tema_period"] = 20
    entry_params["entry_ppo_trending_down_short_threshold"] = trial.suggest_float("entry_ppo_trending_down_short_threshold", 0.3, 0.6)
    entry_params["aroonosc_long_threshold"] = 12.0
    entry_params["entry_trix_trending_up_short_threshold"] = 0.0295774542666676
    entry_params["entry_atr_trending_down_long_threshold"] = 100.0
    entry_params["entry_mfi_trending_down_long_threshold"] = 38.0
    entry_params["macd_histogram_ranging_long_threshold"] = 0.1685
    entry_params["entry_tema_ranging_short_threshold"] = 19250.38045813741
    entry_params["entry_macd_histogram_volatile_long_threshold"] = -0.3565222105032799
    entry_params["entry_ad_short_threshold"] = 0.0
    entry_params["ppo_fast_period"] = 12
    entry_params["ppo_slow_period"] = 26
    params["entry_params"] = entry_params

    # Exit parameters
    exit_params = {}
    exit_params["exit_atr_period"] = trial.suggest_int("exit_atr_period", 10, 30)
    exit_params["exit_trending_down_long_stop_mult"] = trial.suggest_float("exit_trending_down_long_stop_mult", 1.0, 2.5)
    exit_params["exit_trending_down_long_target_mult"] = trial.suggest_float("exit_trending_down_long_target_mult", 1.0, 2.5)
    exit_params["exit_trending_down_long_max_bars"] = trial.suggest_float("exit_trending_down_long_max_bars", 2.0, 6.0)
    exit_params["exit_trending_down_short_stop_mult"] = trial.suggest_float("exit_trending_down_short_stop_mult", 1.0, 2.5)
    exit_params["exit_trending_down_short_target_mult"] = trial.suggest_float("exit_trending_down_short_target_mult", 1.0, 2.5)
    exit_params["exit_trending_up_long_stop_mult"] = 1.571
    exit_params["exit_trending_up_long_target_mult"] = 3.207
    exit_params["exit_trending_up_short_stop_mult"] = 1.2
    exit_params["exit_trending_up_short_target_mult"] = 1.5
    exit_params["exit_trending_up_short_max_bars"] = 3.0
    exit_params["exit_ranging_long_stop_mult"] = 0.919
    exit_params["exit_ranging_long_target_mult"] = 1.098
    exit_params["exit_ranging_long_max_bars"] = 4.8
    exit_params["exit_ranging_short_stop_mult"] = 0.9
    exit_params["exit_ranging_short_target_mult"] = 1.1
    exit_params["exit_ranging_short_max_bars"] = 5.0
    exit_params["exit_volatile_long_stop_mult"] = 2.5
    exit_params["exit_volatile_long_target_mult"] = 1.8
    exit_params["exit_volatile_long_max_bars"] = 4.0
    exit_params["exit_volatile_short_stop_mult"] = 2.948
    exit_params["exit_volatile_short_target_mult"] = 1.77
    exit_params["exit_volatile_short_max_bars"] = 3.83
    params["exit_params"] = exit_params

    # Risk parameters
    risk_params = {}
    risk_params["max_drawdown_pct"] = 15.0
    risk_params["max_concurrent_positions"] = 1
    params["risk_params"] = risk_params

    # Sizer parameters
    sizer_params = {}
    # Shared parameter from exit
    sizer_params["exit_atr_period"] = exit_params["exit_atr_period"]
    sizer_params["risk_per_trade_pct"] = trial.suggest_float("sizer_risk_per_trade_pct", 1.8, 2.5)
    sizer_params["max_position_lots"] = trial.suggest_float("sizer_max_position_lots", 5.0, 8.0)
    sizer_params["marginal_rounding_threshold"] = trial.suggest_float("sizer_marginal_rounding_threshold", 0.3, 0.7)
    # Shared parameter from exit
    sizer_params["exit_trending_up_long_stop_mult"] = exit_params["exit_trending_up_long_stop_mult"]
    # Shared parameter from exit
    sizer_params["exit_trending_up_short_stop_mult"] = exit_params["exit_trending_up_short_stop_mult"]
    # Shared parameter from exit
    sizer_params["exit_trending_down_long_stop_mult"] = exit_params["exit_trending_down_long_stop_mult"]
    # Shared parameter from exit
    sizer_params["exit_trending_down_short_stop_mult"] = exit_params["exit_trending_down_short_stop_mult"]
    # Shared parameter from exit
    sizer_params["exit_ranging_long_stop_mult"] = exit_params["exit_ranging_long_stop_mult"]
    # Shared parameter from exit
    sizer_params["exit_ranging_short_stop_mult"] = exit_params["exit_ranging_short_stop_mult"]
    # Shared parameter from exit
    sizer_params["exit_volatile_long_stop_mult"] = exit_params["exit_volatile_long_stop_mult"]
    # Shared parameter from exit
    sizer_params["exit_volatile_short_stop_mult"] = exit_params["exit_volatile_short_stop_mult"]
    sizer_params["volatile_regime_size_floor"] = trial.suggest_float("sizer_volatile_regime_size_floor", 2.5, 4.5)
    sizer_params["contract_multiplier"] = 5
    sizer_params["initial_capital"] = 200000.0
    params["sizer_params"] = sizer_params

    # Framework requirement
    params["entry_params"]["printlog"] = False
    params["exit_params"]["printlog"] = False
    params["risk_params"]["printlog"] = False
    params["sizer_params"]["printlog"] = False

    return params
