"""
Strategy Parameters - Generated from params_to_optimize.md

This file is AUTO-GENERATED by strategy_params_generator.py
DO NOT EDIT MANUALLY - Changes will be overwritten

To modify parameters:
1. Edit workspace/current/strategy/params_to_optimize.md
2. Run: python -m modules.backtest.backtrader_strategy.platform_agnostic.strategy_params_generator
3. Validate output with parameter_agent.py
"""

from typing import List, Dict, Any
import optuna
from ...core.base.parameter_architecture import (
    ComponentParameterTemplate,
    ParameterSpec,
    ParameterType,
    StrategyParameterFramework
)



class EntryParameters(ComponentParameterTemplate):
    """Parameter definitions for entry component"""

    def get_component_name(self) -> str:
        return 'entry'

    def define_parameters(self) -> List[ParameterSpec]:
        return [
        ParameterSpec(
            name="entry_adx_period",
            param_type=ParameterType.INT,
            default_value=13,
            min_value=10,
            max_value=20,
            description="ADX calculation period for trend confirmation in trending_up LONG and volatile LONG entries (Tier 1 indicator)"
        ),
        ParameterSpec(
            name="entry_mfi_period",
            param_type=ParameterType.INT,
            default_value=11,
            min_value=10,
            max_value=20,
            description="MFI calculation period for ranging LONG oversold detection (Tier 1 indicator)"
        ),
        ParameterSpec(
            name="entry_natr_period",
            param_type=ParameterType.INT,
            default_value=12,
            min_value=10,
            max_value=21,
            description="Normalized ATR period for trending_down LONG volatility spike detection (Tier 1 indicator)"
        ),
        ParameterSpec(
            name="entry_adx_confirmation_threshold",
            param_type=ParameterType.FLOAT,
            default_value=32.21,
            min_value=25.0,
            max_value=40.0,
            description="ADX threshold for trending_up LONG entry confirmation (momentum quality gate)"
        ),
        ParameterSpec(
            name="entry_adxr_threshold",
            param_type=ParameterType.FLOAT,
            default_value=20.62,
            min_value=16.0,
            max_value=19.5,
            description="ADXR threshold for volatile SHORT entry (trend exhaustion detection). [NARROWED by HYP_001] Range tightened from [15,22] to [16,19.5] for post-2023 IC stability."
        ),
        ParameterSpec(
            name="entry_mfi_oversold_threshold",
            param_type=ParameterType.FLOAT,
            default_value=42.93,
            min_value=38.0,
            max_value=43.0,
            description="MFI oversold threshold for ranging LONG entry (mean-reversion). [NARROWED by HYP_001] Range tightened from [32,45] to [38,43] for post-2023 IC stability."
        ),
        ParameterSpec(
            name="entry_natr_threshold",
            param_type=ParameterType.FLOAT,
            default_value=1.81,
            min_value=1.35,
            max_value=1.65,
            description="NATR threshold for trending_down LONG volatility spike entry. [NARROWED by HYP_001] Range tightened from [1.4,2.2] to [1.35,1.65] for post-2023 IC stability."
        ),
        ParameterSpec(
            name="entry_adx_threshold",
            param_type=ParameterType.FIXED,
            default_value=34.27,
            description="ADX threshold for volatile LONG entry signal (FIXED per baseline)"
        ),
        ParameterSpec(
            name="entry_direction_regime_1",
            param_type=ParameterType.FIXED,
            default_value='LONG',
            description="Direction for ranging regime mean-reversion LONG (preserved)"
        ),
        ParameterSpec(
            name="entry_direction_regime_2",
            param_type=ParameterType.FIXED,
            default_value='LONG',
            description="Direction for trending_up regime momentum LONG (preserved)"
        ),
        ParameterSpec(
            name="entry_direction_regime_3",
            param_type=ParameterType.FIXED,
            default_value='SHORT',
            description="Direction for trending_down regime SHORT (preserved)"
        ),
        ParameterSpec(
            name="entry_direction_regime_4",
            param_type=ParameterType.FIXED,
            default_value='LONG',
            description="Direction for trending_down regime volatility LONG (preserved)"
        ),
        ParameterSpec(
            name="entry_direction_regime_5",
            param_type=ParameterType.FIXED,
            default_value='LONG',
            description="Direction for volatile regime LONG (preserved)"
        ),
        ParameterSpec(
            name="entry_direction_regime_6",
            param_type=ParameterType.FIXED,
            default_value='SHORT',
            description="Direction for volatile regime SHORT (preserved)"
        ),
        ParameterSpec(
            name="entry_direction_regime_7",
            param_type=ParameterType.FIXED,
            default_value='SHORT',
            description="Direction for ranging regime SHORT (preserved)"
        ),
        ParameterSpec(
            name="entry_direction_regime_8",
            param_type=ParameterType.FIXED,
            default_value='SHORT',
            description="Direction for trending_up regime SHORT counter-trend exhaustion (preserved)"
        ),
        ParameterSpec(
            name="entry_minus_dm_threshold",
            param_type=ParameterType.FIXED,
            default_value=2875.86,
            description="Minus DM threshold for trending_up SHORT counter-trend entry (FIXED per baseline)"
        ),
        ParameterSpec(
            name="entry_obv_threshold",
            param_type=ParameterType.FIXED,
            default_value=-0.562,
            description="OBV z-score threshold for trending_down SHORT entry (FIXED per baseline)"
        ),
        ParameterSpec(
            name="entry_sar_accel_factor",
            param_type=ParameterType.FIXED,
            default_value=0.02,
            description="SAR acceleration factor for trending_up LONG trend following (FIXED per baseline)"
        ),
        ParameterSpec(
            name="entry_sar_max_accel",
            param_type=ParameterType.FIXED,
            default_value=0.3,
            description="SAR maximum acceleration for trending_up LONG trend following (FIXED per baseline)"
        ),
        ParameterSpec(
            name="entry_willr_overbought_threshold",
            param_type=ParameterType.FIXED,
            default_value=-20.0,
            description="Williams %R overbought threshold for ranging SHORT entry (FIXED per baseline)"
        )
        ]



class ExitParameters(ComponentParameterTemplate):
    """Parameter definitions for exit component"""

    def get_component_name(self) -> str:
        return 'exit'

    def define_parameters(self) -> List[ParameterSpec]:
        return [
        ParameterSpec(
            name="atr_period",
            param_type=ParameterType.INT,
            default_value=20,
            min_value=14,
            max_value=20,
            description="ATR calculation period for trailing stop distance and profit floor volatility scaling (Tier 1 indicator - shared with sizer)"
        ),
        ParameterSpec(
            name="atr_multiplier_ranging",
            param_type=ParameterType.FLOAT,
            default_value=2.75,
            min_value=2.5,
            max_value=3.0,
            description="ATR multiplier for ranging regime trailing stop. [BUG_002 fix] Reduced from 4.0x to 2.75x (range 2.5-3.0) so trailing stop does not reach profit-floor level before floor condition evaluates."
        ),
        ParameterSpec(
            name="atr_multiplier_trending_down",
            param_type=ParameterType.FLOAT,
            default_value=2.75,
            min_value=2.5,
            max_value=3.0,
            description="ATR multiplier for trending_down regime trailing stop. [BUG_002 fix] Reduced from 3.5x to 2.75x (range 2.5-3.0) uniform reduction."
        ),
        ParameterSpec(
            name="atr_multiplier_trending_up",
            param_type=ParameterType.FLOAT,
            default_value=2.75,
            min_value=2.5,
            max_value=3.0,
            description="ATR multiplier for trending_up regime trailing stop. [BUG_002 fix] Reduced from 3.5x to 2.75x (range 2.5-3.0) uniform reduction."
        ),
        ParameterSpec(
            name="atr_multiplier_trending_up_short",
            param_type=ParameterType.FLOAT,
            default_value=2.775,
            min_value=2.7,
            max_value=2.85,
            description="ATR multiplier for trending_up SHORT regime trailing stop. [NARROWED by HYP_002] Range tightened from [2.5, 3.0] to [2.7, 2.85] to address inverted hold ratio (0.66x) where SHORT losers held 20.4 days vs winners 13.5 days."
        ),
        ParameterSpec(
            name="atr_multiplier_volatile",
            param_type=ParameterType.FLOAT,
            default_value=2.75,
            min_value=2.5,
            max_value=3.0,
            description="ATR multiplier for volatile regime trailing stop. [BUG_002 fix] Reduced from 4.0x to 2.75x (range 2.5-3.0) uniform reduction."
        ),
        ParameterSpec(
            name="max_holding_period_ranging",
            param_type=ParameterType.INT,
            default_value=25,
            min_value=15,
            max_value=40,
            description="Maximum holding period in bars for ranging regime (PRESERVED - coordinates with compressible regime duration 10.5±4.0 days)"
        ),
        ParameterSpec(
            name="max_holding_period_trending_down",
            param_type=ParameterType.INT,
            default_value=20,
            min_value=18,
            max_value=22,
            description="Maximum holding period for trending_down regime (PRESERVED - aligns with 12.8±5.8 day persistence)"
        ),
        ParameterSpec(
            name="max_holding_period_trending_up",
            param_type=ParameterType.INT,
            default_value=20,
            min_value=18,
            max_value=25,
            description="Maximum holding period for trending_up regime (PRESERVED - coordinates with 14.0±5.2 day persistence)"
        ),
        ParameterSpec(
            name="profit_protection_activation_r_multiple",
            param_type=ParameterType.FLOAT,
            default_value=2.0,
            min_value=1.5,
            max_value=2.5,
            description="Risk-multiple threshold (R) at which profit-protection floor activates. 2.0R default captures meaningful favorable excursion without premature truncation."
        ),
        ParameterSpec(
            name="profit_protection_floor_atr_multiple",
            param_type=ParameterType.FLOAT,
            default_value=1.0,
            min_value=0.8,
            max_value=1.2,
            description="ATR-based floor width below max_profit_reached. 1.0x default provides profit cushion while allowing continued trend participation."
        ),
        ParameterSpec(
            name="contract_expiry_exit_days",
            param_type=ParameterType.FIXED,
            default_value=3,
            description="Days before contract expiry to force exit (MANDATORY futures constraint)"
        ),
        ParameterSpec(
            name="exit_direction_regime_1",
            param_type=ParameterType.FIXED,
            default_value='LONG',
            description="Exit direction for ranging regime (FIXED per baseline)"
        ),
        ParameterSpec(
            name="exit_direction_regime_2",
            param_type=ParameterType.FIXED,
            default_value='LONG',
            description="Exit direction for trending_up regime LONG pathway (FIXED per baseline)"
        ),
        ParameterSpec(
            name="exit_direction_regime_3",
            param_type=ParameterType.FIXED,
            default_value='SHORT',
            description="Exit direction for trending_down regime SHORT pathway (FIXED per baseline)"
        ),
        ParameterSpec(
            name="exit_direction_regime_4",
            param_type=ParameterType.FIXED,
            default_value='LONG',
            description="Exit direction for volatile regime LONG pathway (FIXED per baseline)"
        ),
        ParameterSpec(
            name="exit_direction_regime_5",
            param_type=ParameterType.FIXED,
            default_value='LONG',
            description="Exit direction for trending_down regime LONG pathway (FIXED per baseline)"
        ),
        ParameterSpec(
            name="exit_direction_regime_6",
            param_type=ParameterType.FIXED,
            default_value='SHORT',
            description="Exit direction for trending_up regime SHORT pathway (FIXED per baseline)"
        ),
        ParameterSpec(
            name="exit_direction_regime_7",
            param_type=ParameterType.FIXED,
            default_value='SHORT',
            description="Exit direction for volatile regime SHORT pathway (FIXED per baseline)"
        ),
        ParameterSpec(
            name="max_holding_period_trending_up_short",
            param_type=ParameterType.FIXED,
            default_value=15,
            description="Maximum holding period for trending_up SHORT (PRESERVED FIXED - separate SHORT pathway logic)"
        ),
        ParameterSpec(
            name="max_holding_period_volatile",
            param_type=ParameterType.FIXED,
            default_value=18,
            description="Maximum holding period for volatile regime (PRESERVED FIXED - aligns with 11.6±5.8 day episode duration)"
        ),
        ParameterSpec(
            name="rolling_high_window",
            param_type=ParameterType.FIXED,
            default_value=5,
            description="Window for rolling high calculation in trailing stop ratchet (FIXED per baseline - Mechanism 2 preservation)"
        ),
        ParameterSpec(
            name="rolling_low_window",
            param_type=ParameterType.FIXED,
            default_value=5,
            description="Window for rolling low calculation in trailing stop ratchet (FIXED per baseline)"
        )
        ]



class RiskParameters(ComponentParameterTemplate):
    """Parameter definitions for risk component"""

    def get_component_name(self) -> str:
        return 'risk'

    def define_parameters(self) -> List[ParameterSpec]:
        return [
        ParameterSpec(
            name="cooldown_bars_after_loss",
            param_type=ParameterType.INT,
            default_value=3,
            min_value=3,
            max_value=3,
            description="Post-loss trading cooldown period in bars; activates on negative closes to prevent revenge trading"
        ),
        ParameterSpec(
            name="max_drawdown_pct",
            param_type=ParameterType.FLOAT,
            default_value=15.0,
            min_value=15.0,
            max_value=15.0,
            description="Maximum portfolio drawdown percentage from equity high-water-mark before mandatory HALT state triggers; hard limit per trading target"
        ),
        ParameterSpec(
            name="max_capital_deployed_pct",
            param_type=ParameterType.FIXED,
            default_value=100.0,
            description="Maximum percentage of capital that may be deployed in positions (structural limit for single-position strategy)"
        ),
        ParameterSpec(
            name="max_concurrent_positions",
            param_type=ParameterType.FIXED,
            default_value=1,
            description="Maximum concurrent positions allowed (structural single-position constraint per baseline architecture)"
        )
        ]



class SizerParameters(ComponentParameterTemplate):
    """Parameter definitions for sizer component"""

    def get_component_name(self) -> str:
        return 'sizer'

    def define_parameters(self) -> List[ParameterSpec]:
        return [
        ParameterSpec(
            name="atr_period",
            param_type=ParameterType.INT,
            default_value=20,
            min_value=14,
            max_value=20,
            description="ATR calculation period shared from exit component for position sizing. PRESERVED from baseline. [SHARED with: exit]"
        ),
        ParameterSpec(
            name="marginal_rounding_threshold",
            param_type=ParameterType.FLOAT,
            default_value=0.406,
            min_value=0.3,
            max_value=0.6,
            description="When raw_size >= threshold AND raw_size < 1.0, round UP to 1 lot. Enables execution in elevated volatility when raw_size falls below 1.0."
        ),
        ParameterSpec(
            name="risk_per_trade_pct",
            param_type=ParameterType.FLOAT,
            default_value=8.5,
            min_value=8.5,
            max_value=8.5,
            description="Risk percentage per trade. Set at 8.5% (break-even_at_median=8.06%) ensuring raw_size >= 1.0 at median ATR and >= 0.8 at p75 ATR with marginal rounding."
        ),
        ParameterSpec(
            name="trailing_atr_multiplier",
            param_type=ParameterType.FLOAT,
            default_value=2.437,
            min_value=2.437,
            max_value=2.437,
            description="ATR multiplier for stop distance in position sizing. Lower than exit multipliers (3.0-4.0x) to ensure sizing adequacy. Shared from exit/sizer logic. PRESERVED FIXED."
        ),
        ParameterSpec(
            name="contract_multiplier",
            param_type=ParameterType.FIXED,
            default_value=5,
            description="SHFE copper futures contract multiplier (5 tons/lot). FIXED per market specification."
        ),
        ParameterSpec(
            name="max_position_lots",
            param_type=ParameterType.FIXED,
            default_value=1,
            description="Maximum position size in lots. HARD CONSTRAINT per trading rules and development history (expansion attempts collapsed oos_risk). PRESERVED per supervisor mandate."
        )
        ]



# Initialize framework and register components
framework = StrategyParameterFramework()
framework.register_component(EntryParameters())
framework.register_component(ExitParameters())
framework.register_component(RiskParameters())
framework.register_component(SizerParameters())

# Generate default parameter structure
DEFAULT_PARAMS = framework.compose_default_strategy()

# Add shared parameters: copy from owner components
DEFAULT_PARAMS['sizer_params']['atr_period'] = DEFAULT_PARAMS['exit_params']['atr_period']



def get_shared_params_mapping() -> Dict[str, Dict[str, Any]]:
    """
    Returns the mapping of shared parameters between components.

    This function is AUTO-GENERATED based on params_to_optimize.json ownership.
    Used by select_best_trial.py to apply optimized values from owner to shared params.

    Returns:
        Dict mapping param_name to {'owner': component_name, 'owner_param': owner_param_name, 'shared_by': [component_names]}
    """
    return {
        "atr_period": {"owner": "exit", "owner_param": "atr_period", "shared_by": ['sizer']},
    }


def apply_shared_params(params: Dict[str, Any]) -> Dict[str, Any]:
    """
    Apply shared parameter values from owner components to all shared components.

    This function is AUTO-GENERATED. It copies optimized parameter values from
    the owner component to all components that share that parameter.

    Handles differently-named shared parameters (e.g., exit_atr_period → sizer_atr_period).

    Args:
        params: Parameter dict with keys like 'component_paramname' (e.g., 'exit_atr_period')

    Returns:
        Updated params dict with shared params filled from owner's values
    """
    shared_mapping = get_shared_params_mapping()

    for param_name, info in shared_mapping.items():
        owner_param = info['owner_param']

        if owner_param in params:
            source_value = params[owner_param]
            params[param_name] = source_value

    return params



def optuna_search_space(trial: optuna.Trial) -> Dict[str, Any]:
    """
    Generate parameter search space for Optuna optimization.

    This function is AUTO-GENERATED with crossover constraints to prevent
    identical period values that cause zero-trade scenarios.
    """
    params = {}

    # Component parameters

    # Entry parameters
    entry_params = {}
    entry_params["entry_adx_period"] = trial.suggest_int("entry_adx_period", 10, 20)
    entry_params["entry_mfi_period"] = trial.suggest_int("entry_mfi_period", 10, 20)
    entry_params["entry_natr_period"] = trial.suggest_int("entry_natr_period", 10, 21)
    entry_params["entry_adx_confirmation_threshold"] = trial.suggest_float("entry_adx_confirmation_threshold", 25.0, 40.0)
    entry_params["entry_adxr_threshold"] = trial.suggest_float("entry_adxr_threshold", 16.0, 19.5)
    entry_params["entry_mfi_oversold_threshold"] = trial.suggest_float("entry_mfi_oversold_threshold", 38.0, 43.0)
    entry_params["entry_natr_threshold"] = trial.suggest_float("entry_natr_threshold", 1.35, 1.65)
    entry_params["entry_adx_threshold"] = 34.27
    entry_params["entry_direction_regime_1"] = 'LONG'
    entry_params["entry_direction_regime_2"] = 'LONG'
    entry_params["entry_direction_regime_3"] = 'SHORT'
    entry_params["entry_direction_regime_4"] = 'LONG'
    entry_params["entry_direction_regime_5"] = 'LONG'
    entry_params["entry_direction_regime_6"] = 'SHORT'
    entry_params["entry_direction_regime_7"] = 'SHORT'
    entry_params["entry_direction_regime_8"] = 'SHORT'
    entry_params["entry_minus_dm_threshold"] = 2875.86
    entry_params["entry_obv_threshold"] = -0.562
    entry_params["entry_sar_accel_factor"] = 0.02
    entry_params["entry_sar_max_accel"] = 0.3
    entry_params["entry_willr_overbought_threshold"] = -20.0
    params["entry_params"] = entry_params

    # Exit parameters
    exit_params = {}
    exit_params["atr_period"] = trial.suggest_int("exit_atr_period", 14, 20)
    exit_params["atr_multiplier_ranging"] = trial.suggest_float("exit_atr_multiplier_ranging", 2.5, 3.0)
    exit_params["atr_multiplier_trending_down"] = trial.suggest_float("exit_atr_multiplier_trending_down", 2.5, 3.0)
    exit_params["atr_multiplier_trending_up"] = trial.suggest_float("exit_atr_multiplier_trending_up", 2.5, 3.0)
    exit_params["atr_multiplier_trending_up_short"] = trial.suggest_float("exit_atr_multiplier_trending_up_short", 2.7, 2.85)
    exit_params["atr_multiplier_volatile"] = trial.suggest_float("exit_atr_multiplier_volatile", 2.5, 3.0)
    exit_params["max_holding_period_ranging"] = trial.suggest_int("exit_max_holding_period_ranging", 15, 40)
    exit_params["max_holding_period_trending_down"] = trial.suggest_int("exit_max_holding_period_trending_down", 18, 22)
    exit_params["max_holding_period_trending_up"] = trial.suggest_int("exit_max_holding_period_trending_up", 18, 25)
    exit_params["profit_protection_activation_r_multiple"] = trial.suggest_float("exit_profit_protection_activation_r_multiple", 1.5, 2.5)
    exit_params["profit_protection_floor_atr_multiple"] = trial.suggest_float("exit_profit_protection_floor_atr_multiple", 0.8, 1.2)
    exit_params["contract_expiry_exit_days"] = 3
    exit_params["exit_direction_regime_1"] = 'LONG'
    exit_params["exit_direction_regime_2"] = 'LONG'
    exit_params["exit_direction_regime_3"] = 'SHORT'
    exit_params["exit_direction_regime_4"] = 'LONG'
    exit_params["exit_direction_regime_5"] = 'LONG'
    exit_params["exit_direction_regime_6"] = 'SHORT'
    exit_params["exit_direction_regime_7"] = 'SHORT'
    exit_params["max_holding_period_trending_up_short"] = 15
    exit_params["max_holding_period_volatile"] = 18
    exit_params["rolling_high_window"] = 5
    exit_params["rolling_low_window"] = 5
    params["exit_params"] = exit_params

    # Risk parameters
    risk_params = {}
    risk_params["cooldown_bars_after_loss"] = trial.suggest_int("risk_cooldown_bars_after_loss", 3, 3)
    risk_params["max_drawdown_pct"] = trial.suggest_float("risk_max_drawdown_pct", 15.0, 15.0)
    risk_params["max_capital_deployed_pct"] = 100.0
    risk_params["max_concurrent_positions"] = 1
    params["risk_params"] = risk_params

    # Sizer parameters
    sizer_params = {}
    # Shared parameter from exit
    sizer_params["atr_period"] = exit_params["atr_period"]
    sizer_params["marginal_rounding_threshold"] = trial.suggest_float("sizer_marginal_rounding_threshold", 0.3, 0.6)
    sizer_params["risk_per_trade_pct"] = trial.suggest_float("sizer_risk_per_trade_pct", 8.5, 8.5)
    sizer_params["trailing_atr_multiplier"] = trial.suggest_float("sizer_trailing_atr_multiplier", 2.437, 2.437)
    sizer_params["contract_multiplier"] = 5
    sizer_params["max_position_lots"] = 1
    params["sizer_params"] = sizer_params

    # Framework requirement
    params["entry_params"]["printlog"] = False
    params["exit_params"]["printlog"] = False
    params["risk_params"]["printlog"] = False
    params["sizer_params"]["printlog"] = False

    return params
