"""
Strategy Parameters - Generated from params_to_optimize.md

This file is AUTO-GENERATED by strategy_params_generator.py
DO NOT EDIT MANUALLY - Changes will be overwritten

To modify parameters:
1. Edit workspace/current/strategy/params_to_optimize.md
2. Run: python -m modules.backtest.backtrader_strategy.platform_agnostic.strategy_params_generator
3. Validate output with parameter_agent.py
"""

from typing import List, Dict, Any
import optuna
from ...core.base.parameter_architecture import (
    ComponentParameterTemplate,
    ParameterSpec,
    ParameterType,
    StrategyParameterFramework
)



class EntryParameters(ComponentParameterTemplate):
    """Parameter definitions for entry component"""

    def get_component_name(self) -> str:
        return 'entry'

    def define_parameters(self) -> List[ParameterSpec]:
        return [
        ParameterSpec(
            name="entry_minus_di_period",
            param_type=ParameterType.FIXED,
            default_value=14,
            description="Calculation period for minus_di indicator. FIXED at standard 14 per PARAMETER_RULES Rule 1 (signal params calculation periods default to standard values)."
        ),
        ParameterSpec(
            name="entry_sma_period",
            param_type=ParameterType.FIXED,
            default_value=20,
            description="Calculation period for SMA indicator. FIXED at standard 20 per PARAMETER_RULES Rule 1."
        ),
        ParameterSpec(
            name="entry_ad_threshold",
            param_type=ParameterType.FLOAT,
            default_value=450000,
            min_value=300000,
            max_value=600000,
            description="Entry threshold for trending_up SHORT. Preserved from baseline. FLOAT per baseline classification."
        ),
        ParameterSpec(
            name="entry_macd_histogram_threshold",
            param_type=ParameterType.FLOAT,
            default_value=14.9158,
            min_value=10,
            max_value=25,
            description="Entry threshold for ranging SHORT. Preserved from baseline. FLOAT per baseline classification."
        ),
        ParameterSpec(
            name="entry_minus_di_threshold",
            param_type=ParameterType.FLOAT,
            default_value=20.58,
            min_value=15,
            max_value=30,
            description="Entry threshold for trending_up LONG. Range ±30% around historical 20.58 (data-justified from development_history). Bounded within typical minus_di range (0-100). FLOAT per PARAMETER_RULES Rule 1."
        ),
        ParameterSpec(
            name="entry_sma_threshold",
            param_type=ParameterType.FLOAT,
            default_value=25000,
            min_value=15000,
            max_value=40000,
            description="Entry threshold for volatile SHORT. Range derived from zinc price scale (typically 20,000-35,000 RMB/ton). Scale-dependent indicator requires instrument-specific thresholds. FLOAT per PARAMETER_RULES Rule 1."
        ),
        ParameterSpec(
            name="entry_natr_threshold",
            param_type=ParameterType.FIXED,
            default_value=2.0271,
            description="Entry threshold for trending_down LONG. Preserved from baseline with FIXED status per preservation mandate."
        ),
        ParameterSpec(
            name="entry_obv_threshold",
            param_type=ParameterType.FIXED,
            default_value=335000,
            description="Entry threshold for ranging LONG. Preserved from baseline_param_classifications. Range [320000, 350000] maintained as FIXED per Rule 4."
        ),
        ParameterSpec(
            name="entry_macd_signal_threshold",
            param_type=ParameterType.FIXED,
            default_value=30,
            description="Entry threshold for trending_down SHORT. Preserved from baseline_param_classifications. Range [-100, 100] maintained as FIXED per Rule 4."
        )
        ]



class ExitParameters(ComponentParameterTemplate):
    """Parameter definitions for exit component"""

    def get_component_name(self) -> str:
        return 'exit'

    def define_parameters(self) -> List[ParameterSpec]:
        return [
        ParameterSpec(
            name="exit_atr_period",
            param_type=ParameterType.INT,
            default_value=13,
            min_value=12,
            max_value=14,
            description="ATR calculation period for stop distance and trailing calculations. FIXED at 13 per baseline preservation and PARAMETER_RULES Rule 1."
        ),
        ParameterSpec(
            name="exit_hard_stop_atr_mult_volatile_short",
            param_type=ParameterType.FLOAT,
            default_value=1.1,
            min_value=0.9,
            max_value=1.3,
            description="Hard stop ATR multiplier for volatile_short pathway. Wider range [0.9, 1.3] allows exploration toward values that reduce 89.2% premature exit rate. FLOAT per PARAMETER_RULES Rule 1."
        ),
        ParameterSpec(
            name="exit_hard_stop_atr_mult_trending_up_long",
            param_type=ParameterType.FLOAT,
            default_value=0.75,
            min_value=0.6,
            max_value=0.9,
            description="Hard stop ATR multiplier for trending_up_long pathway. Range [0.6, 0.9] reflects narrower stops appropriate for trend-following in lower-vol persistence regime. FLOAT per PARAMETER_RULES Rule 1."
        ),
        ParameterSpec(
            name="exit_profit_target_atr_mult_ranging_long",
            param_type=ParameterType.FLOAT,
            default_value=2.0,
            min_value=1.5,
            max_value=2.5,
            description="Profit target multiplier for ranging_long pathway. Preserved from baseline. FLOAT per baseline classification."
        ),
        ParameterSpec(
            name="exit_trailing_activation_atr_mult",
            param_type=ParameterType.FLOAT,
            default_value=1.5,
            min_value=1.0,
            max_value=2.0,
            description="Trailing stop activation threshold multiplier (ATR above entry for LONG, below for SHORT). FLOAT per baseline classification."
        ),
        ParameterSpec(
            name="exit_trailing_atr_multiplier",
            param_type=ParameterType.FLOAT,
            default_value=2.86,
            min_value=2.0,
            max_value=3.5,
            description="Trailing stop distance multiplier (ATR). Used by trailing stop mechanisms (trending_up_long, trending_down_short). FLOAT per baseline classification."
        ),
        ParameterSpec(
            name="exit_time_backstop_trending_up_long",
            param_type=ParameterType.FIXED,
            default_value=17,
            description="Maximum holding period for trending_up_long pathway. Fixed at 17 bars based on 13.2-day avg regime duration minus 1.4-day detection lag. FIXED per PARAMETER_RULES Rule 1."
        ),
        ParameterSpec(
            name="exit_time_backstop_volatile_short",
            param_type=ParameterType.FIXED,
            default_value=20,
            description="Maximum holding period for volatile_short pathway. Preserved at 20 bars per baseline — development_history shows extending volatile backstops causes OOS degradation."
        ),
        ParameterSpec(
            name="exit_time_backstop_trending_down_long",
            param_type=ParameterType.FIXED,
            default_value=11,
            description="Maximum holding period for trending_down_long pathway. Preserved from baseline_strategy."
        ),
        ParameterSpec(
            name="exit_time_backstop_trending_down_short",
            param_type=ParameterType.FIXED,
            default_value=14,
            description="Maximum holding period for trending_down_short pathway. Preserved from baseline_strategy."
        ),
        ParameterSpec(
            name="exit_time_backstop_ranging_long",
            param_type=ParameterType.FIXED,
            default_value=22,
            description="Maximum holding period for ranging_long pathway. Preserved from baseline_strategy."
        ),
        ParameterSpec(
            name="exit_time_backstop_default",
            param_type=ParameterType.FIXED,
            default_value=20,
            description="Default time backstop for ranging_short and trending_up_short pathways. Preserved from baseline_strategy."
        )
        ]



class RiskParameters(ComponentParameterTemplate):
    """Parameter definitions for risk component"""

    def get_component_name(self) -> str:
        return 'risk'

    def define_parameters(self) -> List[ParameterSpec]:
        return [
        ParameterSpec(
            name="recovery_drawdown_buffer_pct",
            param_type=ParameterType.FLOAT,
            default_value=2.35,
            min_value=1.9,
            max_value=2.8,
            description="Default drawdown buffer percentage for ranging regime. FLOAT per baseline classification."
        ),
        ParameterSpec(
            name="recovery_drawdown_buffer_pct_trending_down",
            param_type=ParameterType.FLOAT,
            default_value=3.0,
            min_value=2.0,
            max_value=4.0,
            description="Drawdown buffer percentage for trending_down regime. FLOAT per baseline classification."
        ),
        ParameterSpec(
            name="recovery_drawdown_buffer_pct_trending_up",
            param_type=ParameterType.FLOAT,
            default_value=3.0,
            min_value=2.5,
            max_value=3.5,
            description="Drawdown buffer percentage below max_drawdown_pct required for recovery in trending_up regime. FLOAT per baseline classification."
        ),
        ParameterSpec(
            name="recovery_drawdown_buffer_pct_volatile",
            param_type=ParameterType.FLOAT,
            default_value=1.79,
            min_value=1.52,
            max_value=2.05,
            description="[NARROWED by HYP_001] Drawdown buffer percentage for volatile regime. Range narrowed to ±15% around optimal value 1.785 (was [1.5, 3.5]) to stabilize CV from 0.3013 to target below 0.20. FLOAT per PARAMETER_RULES (infrastructure param requires per-window optimization)."
        ),
        ParameterSpec(
            name="recovery_observation_window_bars",
            param_type=ParameterType.INT,
            default_value=32,
            min_value=26,
            max_value=38,
            description="Default recovery observation window in bars for ranging regime. FLOAT per baseline classification."
        ),
        ParameterSpec(
            name="recovery_observation_window_bars_trending_down",
            param_type=ParameterType.INT,
            default_value=60,
            min_value=40,
            max_value=80,
            description="Recovery observation window in bars for trending_down regime. FLOAT per baseline classification."
        ),
        ParameterSpec(
            name="recovery_observation_window_bars_trending_up",
            param_type=ParameterType.INT,
            default_value=45,
            min_value=35,
            max_value=55,
            description="Recovery observation window in bars for trending_up regime. FLOAT per baseline classification."
        ),
        ParameterSpec(
            name="recovery_observation_window_bars_volatile",
            param_type=ParameterType.INT,
            default_value=45,
            min_value=30,
            max_value=60,
            description="Recovery observation window in bars for volatile regime. FLOAT per baseline classification."
        ),
        ParameterSpec(
            name="max_concurrent_positions",
            param_type=ParameterType.FIXED,
            default_value=1,
            description="Maximum concurrent positions allowed. FIXED at 1 per protected mandate (zero starvation enforcement)."
        ),
        ParameterSpec(
            name="max_drawdown_pct",
            param_type=ParameterType.FIXED,
            default_value=15.0,
            description="Maximum drawdown percentage before trading halt. FIXED at 15.0 per trading_target hard constraint and baseline classification."
        ),
        ParameterSpec(
            name="max_capital_per_trade_pct",
            param_type=ParameterType.FIXED,
            default_value=100,
            description="Maximum capital deployment per trade percentage. FIXED at 100.0 per baseline classification."
        )
        ]



class SizerParameters(ComponentParameterTemplate):
    """Parameter definitions for sizer component"""

    def get_component_name(self) -> str:
        return 'sizer'

    def define_parameters(self) -> List[ParameterSpec]:
        return [
        ParameterSpec(
            name="exit_atr_period",
            param_type=ParameterType.INT,
            default_value=13,
            min_value=12,
            max_value=14,
            description="ATR calculation period for position sizing stop distance estimation. Shared with exit component per baseline architecture. FIXED at 13 per PARAMETER_RULES Rule 1. [SHARED with: exit]"
        ),
        ParameterSpec(
            name="marginal_rounding_threshold",
            param_type=ParameterType.FLOAT,
            default_value=0.34,
            min_value=0.3,
            max_value=0.7,
            description="When raw_size >= threshold AND raw_size < 1.0, round UP to 1 lot to prevent trade starvation. Required per PARAMETER_RULES_CONTEXT Rule 5 for futures with contract_multiplier > 1. FLOAT per PARAMETER_RULES Rule 3 (infrastructure param exempt from signal budget)."
        ),
        ParameterSpec(
            name="risk_per_trade_pct",
            param_type=ParameterType.FIXED,
            default_value=5.0,
            description="[LOCKED by HYP_001] Risk percentage per trade for position sizing. Locked from 5.935% to 5.000% to create ~0.5-1.0% DD buffer below 15% hard limit. CV < 0.1 justifies FIXED status. Above break-even (5.47% is approximate; 5.0% still feasible with marginal rounding rescue at threshold 0.34)."
        ),
        ParameterSpec(
            name="trailing_atr_multiplier",
            param_type=ParameterType.FLOAT,
            default_value=2.86,
            min_value=2.0,
            max_value=3.5,
            description="ATR multiplier for synthetic stop distance in position sizing. Inherited from exit component—sizing uses exit's trailing multiplier for stop distance estimation. [SHARED with: exit]"
        ),
        ParameterSpec(
            name="contract_multiplier",
            param_type=ParameterType.FIXED,
            default_value=5,
            description="SHFE zinc futures contract multiplier (5 tons per lot). FIXED per market specification."
        ),
        ParameterSpec(
            name="max_position_lots",
            param_type=ParameterType.FIXED,
            default_value=2,
            description="Maximum position size in lots. FIXED at 2 per baseline classification. Hard cap enforced after rounding calculation."
        )
        ]



# Initialize framework and register components
framework = StrategyParameterFramework()
framework.register_component(EntryParameters())
framework.register_component(ExitParameters())
framework.register_component(RiskParameters())
framework.register_component(SizerParameters())

# Generate default parameter structure
DEFAULT_PARAMS = framework.compose_default_strategy()

# Add shared parameters: copy from owner components
DEFAULT_PARAMS['sizer_params']['exit_atr_period'] = DEFAULT_PARAMS['exit_params']['exit_atr_period']
DEFAULT_PARAMS['sizer_params']['trailing_atr_multiplier'] = DEFAULT_PARAMS['exit_params']['exit_trailing_atr_multiplier']
# Cross-component shared: entry indicator thresholds used by exit reversal checks
DEFAULT_PARAMS['exit_params']['entry_macd_histogram_threshold'] = DEFAULT_PARAMS['entry_params']['entry_macd_histogram_threshold']
DEFAULT_PARAMS['exit_params']['entry_ad_threshold'] = DEFAULT_PARAMS['entry_params']['entry_ad_threshold']
DEFAULT_PARAMS['exit_params']['entry_natr_threshold'] = DEFAULT_PARAMS['entry_params']['entry_natr_threshold']
DEFAULT_PARAMS['exit_params']['entry_sma_threshold'] = DEFAULT_PARAMS['entry_params']['entry_sma_threshold']
DEFAULT_PARAMS['exit_params']['entry_sma_period'] = DEFAULT_PARAMS['entry_params']['entry_sma_period']



def get_shared_params_mapping() -> Dict[str, Dict[str, Any]]:
    """
    Returns the mapping of shared parameters between components.

    This function is AUTO-GENERATED based on params_to_optimize.json ownership.
    Used by select_best_trial.py to apply optimized values from owner to shared params.

    Returns:
        Dict mapping param_name to {'owner': component_name, 'owner_param': owner_param_name, 'shared_by': [component_names]}
    """
    return {
        "exit_atr_period": {"owner": "exit", "owner_param": "exit_atr_period", "shared_by": ['sizer']},
        "trailing_atr_multiplier": {"owner": "exit", "owner_param": "exit_trailing_atr_multiplier", "shared_by": ['sizer']},
    }


def apply_shared_params(params: Dict[str, Any]) -> Dict[str, Any]:
    """
    Apply shared parameter values from owner components to all shared components.

    This function is AUTO-GENERATED. It copies optimized parameter values from
    the owner component to all components that share that parameter.

    Handles differently-named shared parameters (e.g., exit_atr_period → sizer_atr_period).

    Args:
        params: Parameter dict with keys like 'component_paramname' (e.g., 'exit_atr_period')

    Returns:
        Updated params dict with shared params filled from owner's values
    """
    shared_mapping = get_shared_params_mapping()

    for param_name, info in shared_mapping.items():
        owner_param = info['owner_param']

        if owner_param in params:
            source_value = params[owner_param]
            params[param_name] = source_value

    return params



def optuna_search_space(trial: optuna.Trial) -> Dict[str, Any]:
    """
    Generate parameter search space for Optuna optimization.

    This function is AUTO-GENERATED with crossover constraints to prevent
    identical period values that cause zero-trade scenarios.
    """
    params = {}

    # Component parameters

    # Entry parameters
    entry_params = {}
    entry_params["entry_minus_di_period"] = 14
    entry_params["entry_sma_period"] = 20
    entry_params["entry_ad_threshold"] = trial.suggest_float("entry_ad_threshold", 300000, 600000)
    entry_params["entry_macd_histogram_threshold"] = trial.suggest_float("entry_macd_histogram_threshold", 10, 25)
    entry_params["entry_minus_di_threshold"] = trial.suggest_float("entry_minus_di_threshold", 15, 30)
    entry_params["entry_sma_threshold"] = trial.suggest_float("entry_sma_threshold", 15000, 40000)
    entry_params["entry_natr_threshold"] = 2.0271
    entry_params["entry_obv_threshold"] = 335000
    entry_params["entry_macd_signal_threshold"] = 30
    params["entry_params"] = entry_params

    # Exit parameters
    exit_params = {}
    exit_params["exit_atr_period"] = trial.suggest_int("exit_atr_period", 12, 14)
    exit_params["exit_hard_stop_atr_mult_volatile_short"] = trial.suggest_float("exit_hard_stop_atr_mult_volatile_short", 0.9, 1.3)
    exit_params["exit_hard_stop_atr_mult_trending_up_long"] = trial.suggest_float("exit_hard_stop_atr_mult_trending_up_long", 0.6, 0.9)
    exit_params["exit_profit_target_atr_mult_ranging_long"] = trial.suggest_float("exit_profit_target_atr_mult_ranging_long", 1.5, 2.5)
    exit_params["exit_trailing_activation_atr_mult"] = trial.suggest_float("exit_trailing_activation_atr_mult", 1.0, 2.0)
    exit_params["exit_trailing_atr_multiplier"] = trial.suggest_float("exit_trailing_atr_multiplier", 2.0, 3.5)
    exit_params["exit_time_backstop_trending_up_long"] = 17
    exit_params["exit_time_backstop_volatile_short"] = 20
    exit_params["exit_time_backstop_trending_down_long"] = 11
    exit_params["exit_time_backstop_trending_down_short"] = 14
    exit_params["exit_time_backstop_ranging_long"] = 22
    exit_params["exit_time_backstop_default"] = 20
    # Cross-component shared params: entry indicator thresholds used by exit reversal checks
    # Keys must match exactly what exit.py reads via self.params['entry_*']
    exit_params["entry_macd_histogram_threshold"] = entry_params["entry_macd_histogram_threshold"]
    exit_params["entry_ad_threshold"] = entry_params["entry_ad_threshold"]
    exit_params["entry_natr_threshold"] = entry_params["entry_natr_threshold"]
    exit_params["entry_sma_threshold"] = entry_params["entry_sma_threshold"]
    exit_params["entry_sma_period"] = entry_params["entry_sma_period"]
    params["exit_params"] = exit_params

    # Risk parameters
    risk_params = {}
    risk_params["recovery_drawdown_buffer_pct"] = trial.suggest_float("risk_recovery_drawdown_buffer_pct", 1.9, 2.8)
    risk_params["recovery_drawdown_buffer_pct_trending_down"] = trial.suggest_float("risk_recovery_drawdown_buffer_pct_trending_down", 2.0, 4.0)
    risk_params["recovery_drawdown_buffer_pct_trending_up"] = trial.suggest_float("risk_recovery_drawdown_buffer_pct_trending_up", 2.5, 3.5)
    risk_params["recovery_drawdown_buffer_pct_volatile"] = trial.suggest_float("risk_recovery_drawdown_buffer_pct_volatile", 1.52, 2.05)  # [NARROWED by HYP_001] ±15% around optimal 1.785
    risk_params["recovery_observation_window_bars"] = trial.suggest_int("risk_recovery_observation_window_bars", 26, 38)
    risk_params["recovery_observation_window_bars_trending_down"] = trial.suggest_int("risk_recovery_observation_window_bars_trending_down", 40, 80)
    risk_params["recovery_observation_window_bars_trending_up"] = trial.suggest_int("risk_recovery_observation_window_bars_trending_up", 35, 55)
    risk_params["recovery_observation_window_bars_volatile"] = trial.suggest_int("risk_recovery_observation_window_bars_volatile", 30, 60)
    risk_params["max_concurrent_positions"] = 1
    risk_params["max_drawdown_pct"] = 15.0
    risk_params["max_capital_per_trade_pct"] = 100
    params["risk_params"] = risk_params

    # Sizer parameters
    sizer_params = {}
    # Shared parameter from exit
    sizer_params["exit_atr_period"] = exit_params["exit_atr_period"]
    sizer_params["marginal_rounding_threshold"] = trial.suggest_float("sizer_marginal_rounding_threshold", 0.3, 0.7)
    sizer_params["risk_per_trade_pct"] = 5.0  # [LOCKED by HYP_001] Fixed at 5.0% per CV < 0.1 threshold
    # Shared parameter from exit (inherits exit_trailing_atr_multiplier)
    sizer_params["trailing_atr_multiplier"] = exit_params["exit_trailing_atr_multiplier"]
    sizer_params["contract_multiplier"] = 5
    sizer_params["max_position_lots"] = 2
    params["sizer_params"] = sizer_params

    # Framework requirement
    params["entry_params"]["printlog"] = False
    params["exit_params"]["printlog"] = False
    params["risk_params"]["printlog"] = False
    params["sizer_params"]["printlog"] = False

    return params
